### ISSUE TITLE
Zookeeper Build Problem

### ISSUE THREAD

**Issue by geekyang95** [cocalele/PureFlash#2]
Need a support for libcppunit-1.14 in recent distro like ubuntu 18.04. Because cppunit-1.14 has removed cppunit.m4 from it. We need to update zookeeper to a new version, or just backport their change for cmake building support or just to support pkg-config when there is no cppunit.m4 find. see https://jira.apache.org/jira/browse/ZOOKEEPER-3034 for more details

**Comment by cocalele** [comment]
updating zookeeper to a new version is a good idea. Could you please help to do this upgrade?
