### ISSUE TITLE
Should write redolog after change lmt_entry state

### ISSUE THREAD

**Issue by cocalele** [cocalele/PureFlash#33]
When change an object from RECOVERYING/COPYING to NORMAL state, a redo log should be wrote.
otherwise the data may lost after power outage.
becasuse after power outage, next time system boot on, all object in COPYING/RECOVERYING state will be droped.

**Comment by qiyuanzhi** [comment]
it seems that this atcion has already done at :

https://github.com/cocalele/PureFlash/blob/27584ddfdf89a91dc29bb26e33d21e49aae85284/pfs/src/pf_flash_store.cpp#L1401

https://github.com/cocalele/PureFlash/blob/27584ddfdf89a91dc29bb26e33d21e49aae85284/pfs/src/pf_flash_store.cpp#L2361

does this issue can be closed ?

**Comment by cocalele** [comment]
Yes, this issue has been fixed
