### ISSUE TITLE
Infinity loop to connection to failing node

### ISSUE THREAD

**Issue by cocalele** [cocalele/PureFlash#36]
如果在recovery期间slave节点crash， 那么在primary节点上每次IO的时候就会持续连接slave。

这是因为在recovery开始的时候，primary节点上slave replica被置成了RECOVERYING状态。而在这个状态的副本，仍旧会发送replicate_write

**Comment by qiyuanzhi** [comment]
slave节点crash 之后，conductor没有将副本设置为ERROR状态？

**Comment by cocalele** [comment]
commit 9787725d349a1a068c553be31ef1bda9e0cabb63 fixed this issue
