### ISSUE TITLE
内核客户端从哪里获取

### ISSUE THREAD

**Issue by zphj1987** [cocalele/PureFlash#42]
根据文档内的：
3.5.4 内核态驱动
PureFlash提供了免费的内核态驱动，在物理机上可以直接将pfbd卷呈现成块设备，然后可以格式化成任意的文件系统，任何应用无需API适配就可以访问。
内核驱动非常适合容器PV和数据库场景使用。

这个内核驱动在哪里可以获取到

**Comment by qiyuanzhi** [comment]
当前内核驱动的开放还没有完全准备好，如果想使用内核驱动的话：

1）在pre_build_libs/modules/5.15.0-73-generic目录下有一个Ubuntu 22.04.2 LTS 5.15.0-73-generic 的内核模块，这个是我们当前编译好的驱动，最好可以使用这个发行版本；其他发行版本的话，可以提供一下你使用的os，kernel版本；

2） 可以使用iscsi对接；

**Comment by zphj1987** [comment]
好到 收到 谢谢
