### ISSUE TITLE
Simple IO run

### ISSUE THREAD

**Issue by geekyang95** [cocalele/PureFlash#5]
Need a simple demo to check afs_store Local IO path. My plan:
1. run it as a unittest. use gtest/gmock to do, will add a submodule.
2. only check IO / volume meta data, without network part.
3. mock metadata initialize, only a few metadata is needed for testing purpose 
3. write a memstore to store testing data. It's core part is a map<size_t offset, void *data>. It will be 
    very fast for testing purpose than write to a file.

**Comment by cocalele** [comment]
I think it's more simple to use a file rather than to construct a memstore, because S5FlashStore communicate to system only via a file descirptor(`S5FlashStore::dev_fd`). Create memstore may need a lot coding work.

**Comment by geekyang95** [comment]
That's not a problem, only a little code changes need to make by using gmock to mock read/write operations. Maybe I should write a simple demo for discussing, at first.

**Comment by geekyang95** [comment]
And, it would be a good idea to seperate OS operations from S5FlashStore, because we may need to support spdk in the future, or like the test purpose. If we can make dev_handle_t more powerful (not just a file descripter), it would be much easier to do things like that.
That's a more CPP way to solve problem :)

**Comment by geekyang95** [comment]
#9
