### ISSUE TITLE
建议/var/log/pfs.log的启动日志里面可以把git commit id加上，再使用git checkou “ commit id”，方便定位log对应代码的行数

### ISSUE THREAD

**Issue by yunwoniu** [cocalele/PureFlash#50]
![image](https://github.com/cocalele/PureFlash/assets/78011553/390abb0d-149f-414e-8ecc-aa5c960ea868)

**Comment by cocalele** [comment]
master最新代码已经加上。
![image](https://github.com/cocalele/PureFlash/assets/16593429/882a8583-0b51-47c5-a11d-abdd90002fa9)
