### ISSUE TITLE
了解一下咱们这个项目和purestorage公司的产品有关系吗

### ISSUE THREAD

**Issue by changyonggang** [cocalele/PureFlash#66]
purestorage公司网站：https://www.purestorage.com/cn/；这是该公司简介：
Pure Storage是一家全球领先的全闪存存储解决方案提供商，成立于2009年10月，总部位于美国加利福尼亚州山景城。该公司专注于研发和销售企业级的全固态存储阵列以及相关数据服务，旨在帮助企业实现数据中心现代化，并通过简化数据存储架构来提升性能、降低运营成本及复杂性。

Pure Storage的核心产品线是Pure FlashArray系列，它以全闪存技术为基础，结合创新的数据压缩、重复数据删除和其他优化功能，为关键业务应用提供极高的I/O性能、低延迟以及出色的可用性和可扩展性。此外，Pure Storage还提供了FlashBlade产品，专为大规模并行非结构化数据处理设计，适用于大数据分析、机器学习和内容库等场景。

除了硬件产品，Pure Storage也发展了软件和服务方面的产品组合，包括数据保护、云集成解决方案（如支持混合云和多云环境下的数据移动与管理）以及用于容器环境的存储解决方案（如Portworx by Pure Storage）。

随着云计算和数字化转型的深入，Pure Storage持续致力于通过其先进的存储技术推动企业的数据战略，帮助客户适应不断变化的市场和技术趋势，实现数据驱动的业务增长和效率提升。

**Comment by cocalele** [comment]
PureFlash和Pure stoage没有任何关系。

PureFlash这名字最初的意思是我们是为全闪存优化的方案，纯粹的闪存。（当然，也许翻译的不好 ^-^）

PureFlash发展到今天已经不仅仅支持全闪存，还支持混闪。为了还会支持MBR，ZNS等低成本介质。

感谢关注！

**Comment by changyonggang** [comment]
> PureFlash和Pure stoage没有任何关系。
> 
> PureFlash这名字最初的意思是我们是为全闪存优化的方案，纯粹的闪存。（当然，也许翻译的不好 ^-^）
> 
> PureFlash发展到今天已经不仅仅支持全闪存，还支持混闪。为了还会支持MBR，ZNS等低成本介质。
> 
> 感谢关注！

谢谢回复
