### ISSUE TITLE
trim_proc线程出现段错误

### ISSUE THREAD

**Issue by ericqzhao** [cocalele/PureFlash#68]
<img width="1670" alt="4d6215af823c877bbbab53fb6a0d08b" src="https://github.com/cocalele/PureFlash/assets/125110732/8190e2eb-b7fc-4e9c-81d7-954b2d1c273c">

**Comment by ericqzhao** [comment]
现象：就是trim_proc执行了1024次后，在调用store的post_event的时候出现了段错误，如上图所示；原因是：msg_cache_locked列表为空；
根因：因为trim_proc线程没有设置tls，因此使用的是store的msg_cache_locked，当store执行process_event完成后，归还到的是msg_cache，导致msg_cache_locked为空

**Comment by ericqzhao** [comment]
<img width="358" alt="1705649334856" src="https://github.com/cocalele/PureFlash/assets/125110732/7f377a94-e4ed-4daa-a84a-ccbe1260e74c">

**Comment by cocalele** [comment]
good job!
