### ISSUE TITLE
Give store device a formal and peculiar name 

### ISSUE THREAD

**Issue by cocalele** [cocalele/PureFlash#8]
We have use 'store' as name of a storage device in AFS node. but store is too common a word, and cause chaos in later discussion and documentation.
We need a more formal and a peculiar name for store device, like the word ‘OSD’ used in ceph.

**Comment by geekyang95** [comment]
Yes. As my suggestion, Call it **Node** or **Instance**. And the word **store** should give to device structure.

 I've write some code for new dev_handle_t, maybe we could use the new name. And also for connection, I suggest to use a more comon base class to manage it. Then we can write both Tcp or RDMA as a subclass for it.

**Comment by cocalele** [comment]
So, as your suggestion, **Node** as the overall name of `s5afs` service running on a machine. **store** to represent a disk( SSD, or HDD, or a loop back device in testing). This is the name currently in use.

OK, let's keep current status.

**Comment by cocalele** [comment]
> So, as your suggestion, **Node** as the overall name of `s5afs` service running on a machine. **store** to represent a disk( SSD, or HDD, or a loop back device in testing). This is the name currently in use.
> 
> OK, let's keep current status.

To the continuous of this project, it's better to use the word **store** for s5afs service, and **tray** for a single disk(SSD, HDD, etc). These word has already used in code to register on ZK.

Of course, I'll give some explain in the readme doc.

**Comment by geekyang95** [comment]
#9
